```{r}
# Load the necessary packages
library(dplyr)
```

```{r}
# Read the data frame
dataset <- read.csv("../data/raw/noshow_hosptial_appointment.csv")
print(dataset)
```

```{r}
sum(is.na(dataset))
```

```{r}
# Renaming columns to fix inconsistencies and misspellings
colnames(dataset)[which(colnames(dataset) == "Hipertension")] <- "Hypertension"
colnames(dataset)[which(colnames(dataset) == "Handcap")] <- "Handicapped"
colnames(dataset)[which(colnames(dataset) == "SMS_received")] <- "SMSReceived"
colnames(dataset)[which(colnames(dataset) == "No.show")] <- "Cancelled"

colnames(dataset)
```

```{r}
dataset$ScheduledDayTemp <- dataset$ScheduledDay

# Convert the date columns to datetime
dataset$AppointmentDay <- as.Date(dataset$AppointmentDay)
dataset$ScheduledDayTemp <- as.Date(dataset$ScheduledDayTemp)

print(unique(format(dataset$ScheduledDayTemp, "%Y")))

```

```{r}
# This field will help us see the waiting time till the appointment for better insights 
dataset$DaysWaited <- as.numeric(as.Date(dataset$AppointmentDay) -
                                   as.Date(dataset$ScheduledDayTemp))


any(dataset$DaysWaited < 0)
```
```{r}
dataset <- dataset[dataset$DaysWaited >= 0,]
any(dataset$DaysWaited < 0)
```

```{r}
dataset$ScheduledDayTemp <- NULL # Lets delete this now that we do not require it

# Since this column has time in addition to the date we shall convert the data into 
# the POSIXct datatype

dataset$ScheduledDay <- as.POSIXct(dataset$ScheduledDay, format = "%Y-%m-%dT%H:%M:%SZ")
```

```{r}
# Creating Column for the day of week that the appointment was scheduled to.
dataset$DayOfWeek <- weekdays(as.Date(dataset$ScheduledDay))
```

```{r}
print(any(dataset$Age < 0))
```

```{r}
# Removing ages less than 0 as they are data entry errors
dataset <- dataset[dataset$Age >= 0,]

print(any(dataset$Age < 0))
```
```{r}
print(min(dataset$Age))
print(max(dataset$Age))
```

```{r}
# Define the age bin edges
age_bins <- c(-1, 2, 16, 30, 45, 116)
# Define the age group labels
age_labels <- c('Baby', 'Children', 'YoungAdult', 'MiddleAgedAdult', 'OldAdult')

dataset$AgeGroup <- cut(dataset$Age, age_bins, labels = age_labels)
print(unique(dataset$AgeGroup))
```


```{r}
# Calculate total number of appointments for each patient
dataset <- dataset %>% 
  group_by(PatientId) %>%  
  mutate(TotalAppointments = n()) %>% 
  ungroup()

# Calculate number of appointments cancelled by each patient
dataset <- dataset %>% 
  group_by(PatientId) %>%  
  mutate(NoOfAppointmentsCancelled = sum(Cancelled == "Yes")) %>% 
  ungroup()

# Calculate percentage of appointments cancelled by each patient
dataset <- dataset %>% 
  mutate(CancelledPercentage = round(NoOfAppointmentsCancelled / TotalAppointments * 100, 2))
```

```{r}
# For binary columns encode, here the values are being categorized into booleans
dataset$Cancelled<- ifelse(dataset$Cancelled == "Yes", TRUE, FALSE)
dataset$Scholarship<- ifelse(dataset$Scholarship == 1, TRUE, FALSE)
dataset$Hypertension<- ifelse(dataset$Hypertension == 1, TRUE, FALSE)
dataset$Handicapped <- ifelse(dataset$Handicapped > 0, TRUE, FALSE)
dataset$Diabetes<- ifelse(dataset$Diabetes == 1, TRUE, FALSE)
dataset$Alcoholism<- ifelse(dataset$Alcoholism == 1, TRUE, FALSE)
dataset$SMSReceived<- ifelse(dataset$SMSReceived == 1, TRUE, FALSE)
```

```{r}
write.csv(dataset, "../data/processed/final.csv", row.names=FALSE)
```
